# Generated by Django 4.0.1 on 2022-11-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_delete_boxlog'),
        ('users', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxRFIDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=255)),
                ('last_register', models.DateField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.box')),
            ],
        ),
        migrations.CreateModel(
            name='BoxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.box')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.offer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companyworker')),
            ],
        ),
    ]
