# Generated by Django 4.0.1 on 2022-11-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boxrfidlog',
            name='last_register',
            field=models.DateTimeField(),
        ),
    ]
