# Generated by Django 4.0.1 on 2022-11-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcontract',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='virtualcontract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier'),
        ),
        migrations.AddField(
            model_name='boxlog',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.box'),
        ),
        migrations.AddField(
            model_name='boxlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='boxlog',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companyworker'),
        ),
        migrations.AddField(
            model_name='box',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='allowedworkers',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.box'),
        ),
        migrations.AddField(
            model_name='allowedworkers',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='allowedworkers',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companyworker'),
        ),
    ]
