# Generated by Django 4.0.1 on 2022-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='box',
            name='last_activity',
            field=models.DateTimeField(null=True),
        ),
    ]
