# Generated by Django 4.0.1 on 2022-11-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_box_is_active_box_last_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoxLog',
        ),
    ]
