# Generated by Django 4.0.1 on 2022-11-14 12:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'StartPoint'), ('A', 'Accepted'), ('D', 'Delivered'), ('G', 'Got')], default='S', max_length=1)),
                ('rating', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.box')),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.suppliercourier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companyworker')),
            ],
        ),
    ]
